// <auto-generated />
using System;
using Geotrend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geotrend.Infrastructure.Migrations
{
    [DbContext(typeof(GeotrendDbContext))]
    [Migration("20260927021737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geotrend.Domain.Entities.Barragem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NivelAlertaAtual")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Barragem", (string)null);
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Instrumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarragemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("LimiteAlerta")
                        .HasColumnType("double precision");

                    b.Property<double>("LimiteAtencao")
                        .HasColumnType("double precision");

                    b.Property<double>("LimiteEmergencia")
                        .HasColumnType("double precision");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarragemId");

                    b.ToTable("Instrumentos", (string)null);
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Leitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstrumentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("Leituras", (string)null);
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Instrumento", b =>
                {
                    b.HasOne("Geotrend.Domain.Entities.Barragem", null)
                        .WithMany("Instrumentos")
                        .HasForeignKey("BarragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Leitura", b =>
                {
                    b.HasOne("Geotrend.Domain.Entities.Instrumento", null)
                        .WithMany("Leituras")
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Barragem", b =>
                {
                    b.Navigation("Instrumentos");
                });

            modelBuilder.Entity("Geotrend.Domain.Entities.Instrumento", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
